{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-usemodels
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/usemodels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/usemodels/usemodels_{{ version }}.tar.gz
  sha256: 510ff71bbe7209bc5723c3e0ef090ef8617d3ca853c3db9818452edbc82687b5

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-clipr
    - r-dplyr
    - r-purrr
    - r-recipes >=0.1.15
    - r-rlang
    - r-tidyr
    - r-tune >=0.1.2
  run:
    - r-base
    - r-cli
    - r-clipr
    - r-dplyr
    - r-purrr
    - r-recipes >=0.1.15
    - r-rlang
    - r-tidyr
    - r-tune >=0.1.2

test:
  commands:
    - $R -e "library('usemodels')"           # [not win]
    - "\"%R%\" -e \"library('usemodels')\""  # [win]

about:
  home: https://usemodels.tidymodels.org/
  dev_url: https://github.com/tidymodels/usemodels
  license: MIT
  summary: Code snippets to fit models using the tidymodels framework can be easily created for
    a given data set.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: usemodels
# Title: Boilerplate Code for 'Tidymodels' Analyses
# Version: 0.2.0
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-2402-136X")), person("RStudio", role = "cph") )
# Description: Code snippets to fit models using the tidymodels framework can be easily created for a given data set.
# License: MIT + file LICENSE
# URL: https://usemodels.tidymodels.org/, https://github.com/tidymodels/usemodels
# BugReports: https://github.com/tidymodels/usemodels/issues
# Imports: cli, clipr, dplyr, purrr, recipes (>= 0.1.15), rlang, tidyr, tune (>= 0.1.2)
# Suggests: covr, modeldata, spelling, testthat
# Config/Needs/website: tidyverse/tidytemplate
# Config/testthat/edition: 3
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.1.2
# NeedsCompilation: no
# Packaged: 2022-02-18 20:14:14 UTC; max
# Author: Max Kuhn [aut, cre] (<https://orcid.org/0000-0003-2402-136X>), RStudio [cph]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2022-02-18 22:10:02 UTC
